[package]
name = "ipfs"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
reqwest = "0.12.9"
thiserror = "2.0.3"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
grc20 = { version = "0.1.0", path = "../grc20" }
